/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaempresa;

import javax.swing.table.DefaultTableModel;
import sistemaempresa.models.Empleado;
import sistemaempresa.models.Empresa;


/**
 *
 * @author Ivan
 */
public class VistaEmpleado extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        
        @Override
        public boolean isCellEditable(int f, int c) {
            
            return false;
            
        }
    };
    public VistaEmpleado() {
        initComponents();
        armarCabecera();
        borrarFilas();
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpresa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtEmpleados = new javax.swing.JTextField();

        jtEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtEmpresa);

        jLabel1.setText("Buscar por Nombre o Inicial ( A-Z)");

        jtEmpleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtEmpleadosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jtEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEmpleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmpleadosKeyReleased
      borrarFilas();
      for(Empresa empresa :EmpresaIF.empresas ){
          for(Empleado empleado:empresa.getEmpleados()){
              if(empleado.getNombreApellido().startsWith(jtEmpleados.getText())){
                  
                  modelo.addRow(new Object[]{
                  empleado.getNombreApellido(),
                  empleado.getDni(),
                  empleado.getCategoria(),
                  empleado.getSueldo()
              
              });
              
            }
              
        }
      }
    }//GEN-LAST:event_jtEmpleadosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtEmpleados;
    private javax.swing.JTable jtEmpresa;
    // End of variables declaration//GEN-END:variables

   private void armarCabecera(){
       
      modelo.addColumn("Nombre y Apellido");
      modelo.addColumn("DNI");
      modelo.addColumn("Categoria");
      modelo.addColumn("Sueldo");
      jtEmpresa.setModel(modelo);
       
   }
           
  
   
         private void mostrarFilas(Empresa empresa){
             borrarFilas();
             for(Empleado empleado: empresa.getEmpleados()){
                 modelo.addRow(new Object[] {empleado.getNombreApellido(),empleado.getDni(),empleado.getCategoria(),empleado.getSueldo()});
             }
         }
    
      private void borrarFilas(){
          int f = modelo.getRowCount()-1;
        
          
          for(; f>=0;f--){
              modelo.removeRow(f);
          }
         
              
      }
           
    }
      
     
          
          
          
        
      
       
        
        
        
        
  
